In [1]:
import numpy as np
import matplotlib.pyplot as plt

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
input = np.array([[0, 0], [0, 0.5], [0, 1],
                  [0.5, 0], [0.5, 0.5], [0.5, 1],
                  [1, 0], [1, 0.5], [1, 1]])

expected = np.array([0, 0, 0,
                     0, 0, 1,
                     0, 1, 1])

In [ ]:
# Extract x and y coordinates separately
x_coords = x[:, 0]
y_coords = x[:, 1]

# Plot the data
plt.scatter(x_coords[y == 0], y_coords[y == 0], color='blue')
plt.scatter(x_coords[y == 1], y_coords[y == 1], color='red')
plt.show()

In [258]:
W0 = np.array([[0.61275508, 0.98539237, 0.27266151],
               [0.47399039, 0.66266751, 0.72721264]])
W1 = np.array([[0.96787958],
               [0.80183257],
               [0.94478099]])

In [421]:
hidden = np.matmul(input, W0)
out = np.matmul(hidden, W1)

loss = abs(out - expected).sum()
loss

hidden
np.column_stack([out, expected])

40.41643842348143

array([[ 0.        ,  0.        ,  0.        ],
       [ 0.05676384,  0.05811096,  0.19726479],
       [ 0.11352768,  0.11622192,  0.39452959],
       [ 0.12614619,  0.21947339, -0.03001077],
       [ 0.18291003,  0.27758435,  0.16725402],
       [ 0.23967387,  0.33569531,  0.36451882],
       [ 0.25229237,  0.43894678, -0.06002154],
       [ 0.30905621,  0.49705774,  0.13724325],
       [ 0.36582005,  0.5551687 ,  0.33450805]])

array([[0.        , 0.        ],
       [0.26172066, 0.        ],
       [0.52344131, 0.        ],
       [0.23518447, 0.        ],
       [0.49690513, 0.        ],
       [0.75862578, 1.        ],
       [0.47036894, 0.        ],
       [0.7320896 , 1.        ],
       [0.99381025, 1.        ]])

In [422]:
dLdW1 = (np.sign(out.squeeze() - expected) * hidden.T).sum(axis=1)
dLdW1

dHiddendW0 = np.tile(input.sum(axis = 0), (3, 1)).T
dHiddendW0

dLdW0 = dHiddendW0 * dLdW1
dLdW0


array([-0.18291003, -0.27758435, -0.16725402])

array([[4.5, 4.5, 4.5],
       [4.5, 4.5, 4.5]])

array([[-0.82309512, -1.24912958, -0.75264311],
       [-0.82309512, -1.24912958, -0.75264311]])

In [423]:
e = 0.001
W0 -= e * dLdW0
W1 -= (e * dLdW1).reshape(3, 1)

W0
W1

array([[ 0.25311547,  0.44019591, -0.0592689 ],
       [ 0.11435078,  0.11747105,  0.39528223]])

array([[0.88795967],
       [0.6806778 ],
       [0.87101868]])