In [4]:
import numpy as np

In [245]:
input = np.array([[0, 0], [0, 0.5], [0, 1],
                  [0.5, 0], [0.5, 0.5], [0.5, 1],
                  [1, 0], [1, 0.5], [1, 1]])

expected = np.array([0, 0, 0,
                     0, 0, 1,
                     0, 1, 1])

In [246]:
W0 = np.array([[0.61275508, 0.98539237, 0.27266151],
               [0.47399039, 0.66266751, 0.72721264]])
W1 = np.array([[0.96787958],
               [0.80183257],
               [0.94478099]])

In [247]:
hidden = np.matmul(input, W0)
out = np.matmul(hidden, W1)

loss = abs(out - expected).sum()
loss

hidden
np.column_stack([out, expected])

115.42383478039508

array([[0.        , 0.        , 0.        ],
       [0.23699519, 0.33133376, 0.36360632],
       [0.47399039, 0.66266751, 0.72721264],
       [0.30637754, 0.49269619, 0.13633075],
       [0.54337273, 0.82402994, 0.49993707],
       [0.78036793, 1.1553637 , 0.86354339],
       [0.61275508, 0.98539237, 0.27266151],
       [0.84975027, 1.31672612, 0.63626783],
       [1.08674547, 1.64805988, 0.99987415]])

array([[0.        , 0.        ],
       [0.83858535, 0.        ],
       [1.67717069, 0.        ],
       [0.82039912, 0.        ],
       [1.65898446, 0.        ],
       [2.49756981, 1.        ],
       [1.64079824, 0.        ],
       [2.47938358, 1.        ],
       [3.31796893, 1.        ]])

In [243]:
dLdW1 = (np.sign(out.squeeze() - expected) * hidden.T).sum(axis=1)
dLdW1

dHiddendW0 = np.tile(input.sum(axis = 0), (3, 1)).T
dHiddendW0

dLdW0 = dHiddendW0 * dLdW1
dLdW0


array([-0.18197936, -0.27617197, -0.16640302])

array([[4.5, 4.5, 4.5],
       [4.5, 4.5, 4.5]])

array([[-0.81890712, -1.24277388, -0.74881358],
       [-0.81890712, -1.24277388, -0.74881358]])

In [244]:
e = 0.001
W0 -= e * dLdW0
W1 -= (e * dLdW1).reshape(3, 1)

W0
W1

array([[ 0.25218061,  0.43877718, -0.06012373],
       [ 0.11341592,  0.11605232,  0.3944274 ]])

array([[0.88775192],
       [0.68036253],
       [0.87082871]])